image: "centos:8"

stages:
  - buildUiService

buildAuthService:
  stage: buildUiService
  tags:
    - AMD64
  script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install docker-ce docker-ce-cli containerd.io --nobest -y
    - wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
    - tar -xzf go1.14.2.linux-amd64.tar.gz
    - ls
    - ls go
    - ls go/bin
    - ./go/bin/go build ui-service/main.go
    - docker login -u 'alexandruubytex' -p '333Albastru333'
    - docker build -t alexandruubytex/golang_marketplace_auth_service:latest .
    - docker push alexandruubytex/golang_marketplace_auth_service:latest

