image: "docker:18.09.7"

services:
  - docker:18.09.7-dind

stages:
  - buildUiService

buildAuthService:
  stage: buildUiService
  tags:
    - AMD64
  script:
    - wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
    - tar -xzv go1.14.2.linux-amd64.tar.gz
    - ./go/bin/go build main.go
    - docker login -u 'alexandruubytex' -p '333Albastru333'
    - docker build -t alexandruubytex/golang_marketplace_auth_service:latest .
    - docker push alexandruubytex/golang_marketplace_auth_service:latest

