image: "docker:18.09.7"

services:
  - docker:18.09.7-dind

stages:
  - buildAuthService

buildAuthService:
  stage: buildAuthService
  tags:
    - AMD64
  script:
    - apk add go
    - apk add libc-dev

    - cd auth-service
    - go build -o bin/main main.go
    - rm -rf *.go

    - docker login -u 'alexandruubytex' -p '333Albastru333'
    - docker build -t alexandruubytex/golang_marketplace_auth_service:latest auth-service
    - docker push alexandruubytex/golang_marketplace_auth_service:latest

