image: "golang"

stages:
  - buildUiService

buildAuthService:
  stage: buildUiService
  tags:
    - AMD64
  script:
    # - apt-get install -y yum-utils
    # - apt-get install wget -y
    # - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    # - yum install docker-ce docker-ce-cli containerd.io -y
    # - systemctl start docker

    ####### debian ##########
    - apt-get install apt-transport-https ca-certificates curl gnupg-agent
    - curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    - apt-key fingerprint 0EBFCD88
    - add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get update
    - apt-get install docker-ce docker-ce-cli containerd.io
    ############

    # - wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
    # - tar -xzf go1.14.2.linux-amd64.tar.gz
    - ./go/bin/go build ui-service/main.go

    - docker login -u 'alexandruubytex' -p '333Albastru333'
    - docker build -t alexandruubytex/golang_marketplace_auth_service:latest auth-service
    - docker push alexandruubytex/golang_marketplace_auth_service:latest

